trigger: none

resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure

jobs:
  - template: ../../eng/pipelines/templates/jobs/archetype-sdk-tests.yml
    parameters:
      MaxParallel: 1
      ServiceDirectory: cosmos
      TestMarkArgument: not globaldb
      EnvVars:
        ACCOUNT_KEY: $(python-cosmos-live-account-key)
        ACCOUNT_HOST: $(python-cosmos-live-account-host)

      # Workaround to ensure deletion of databases from a statically defined
      # CosmosDB account.
      BeforeTestSteps:
        - pwsh: |
            $testDatabaseId = "Python Test Database " + (New-Guid).ToString()
            Write-Host Test Database ID: $testDatabaseId
            Write-Host "##vso[task.setvariable variable=COSMOS_TEST_DATABASE_ID]$testDatabaseId"
          displayName: Set COSMOS_TEST_DATABASE_ID
      AfterTestSteps:
        - pwsh: |
            python sdk/cosmos/azure-cosmos/test/cleanup.py $env:COSMOS_TEST_DATABASE_ID
          displayName: Cleanup test database
